name: task_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  talker: ^4.3.0
  talker_flutter: ^4.3.0
  talker_bloc_logger: ^4.4.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.0
  fluttertoast: ^8.2.8
  flutter_vibrate: ^1.3.0
  json_annotation: ^4.9.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VKSansDisplay
      fonts:
        - asset: fonts/VKSansDisplay-Regular.ttf
        - asset: fonts/VKSansDisplay-Medium.ttf
          weight: 500
        - asset: fonts/VKSansDisplay-Bold.ttf
          weight: 700
        - asset: fonts/VKSansDisplay-DemiBold.ttf
          weight: 600